[build]
  publish = "."

[[headers]]
  for = "*.wasm"
  [headers.values]
    Content-Type = "application/wasm"
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"

[[headers]]
  for = "*.iso"
  [headers.values]
    Content-Type = "application/octet-stream"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.bin"
  [headers.values]
    Content-Type = "application/octet-stream"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"

# Handle large file downloads with longer timeouts
[[redirects]]
  from = "/*.iso"
  to = "/:splat.iso"
  status = 200
  force = false

[[redirects]]
  from = "/*.wasm"
  to = "/:splat.wasm" 
  status = 200
  force = false 